/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Kandy - Preview
 * This is the public Kandy REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import PreviewBase from "../PreviewBase";
import Version from "../../base/Version";
import { AssistantListInstance } from "./understand/assistant";

export default class Understand extends Version {
  /**
   * Initialize the Understand version of Preview
   *
   * @param domain - The Kandy (Kandy.Preview) domain
   */
  constructor(domain: PreviewBase) {
    super(domain, "understand");
  }

  /** assistants - { Kandy.Preview.Understand.AssistantListInstance } resource */
  protected _assistants?: AssistantListInstance;

  /** Getter for assistants resource */
  get assistants(): AssistantListInstance {
    this._assistants = this._assistants || AssistantListInstance(this);
    return this._assistants;
  }
}
