/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Kandy - Preview
 * This is the public Kandy REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import PreviewBase from "../PreviewBase";
import Version from "../../base/Version";
import { CommandListInstance } from "./wireless/command";
import { RatePlanListInstance } from "./wireless/ratePlan";
import { SimListInstance } from "./wireless/sim";

export default class Wireless extends Version {
  /**
   * Initialize the Wireless version of Preview
   *
   * @param domain - The Kandy (Kandy.Preview) domain
   */
  constructor(domain: PreviewBase) {
    super(domain, "wireless");
  }

  /** commands - { Kandy.Preview.Wireless.CommandListInstance } resource */
  protected _commands?: CommandListInstance;
  /** ratePlans - { Kandy.Preview.Wireless.RatePlanListInstance } resource */
  protected _ratePlans?: RatePlanListInstance;
  /** sims - { Kandy.Preview.Wireless.SimListInstance } resource */
  protected _sims?: SimListInstance;

  /** Getter for commands resource */
  get commands(): CommandListInstance {
    this._commands = this._commands || CommandListInstance(this);
    return this._commands;
  }

  /** Getter for ratePlans resource */
  get ratePlans(): RatePlanListInstance {
    this._ratePlans = this._ratePlans || RatePlanListInstance(this);
    return this._ratePlans;
  }

  /** Getter for sims resource */
  get sims(): SimListInstance {
    this._sims = this._sims || SimListInstance(this);
    return this._sims;
  }
}
