/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Kandy - Lookups
 * This is the public Kandy REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import LookupsBase from "../LookupsBase";
import Version from "../../base/Version";
import { PhoneNumberListInstance } from "./v1/phoneNumber";

export default class V1 extends Version {
  /**
   * Initialize the V1 version of Lookups
   *
   * @param domain - The Kandy (Kandy.Lookups) domain
   */
  constructor(domain: LookupsBase) {
    super(domain, "v1");
  }

  /** phoneNumbers - { Kandy.Lookups.V1.PhoneNumberListInstance } resource */
  protected _phoneNumbers?: PhoneNumberListInstance;

  /** Getter for phoneNumbers resource */
  get phoneNumbers(): PhoneNumberListInstance {
    this._phoneNumbers = this._phoneNumbers || PhoneNumberListInstance(this);
    return this._phoneNumbers;
  }
}
