/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Kandy - Verify
 * This is the public Kandy REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import VerifyBase from "../VerifyBase";
import Version from "../../base/Version";
import { FormListInstance } from "./v2/form";
import { SafelistListInstance } from "./v2/safelist";
import { ServiceListInstance } from "./v2/service";
import { TemplateListInstance } from "./v2/template";
import { VerificationAttemptListInstance } from "./v2/verificationAttempt";
import { VerificationAttemptsSummaryListInstance } from "./v2/verificationAttemptsSummary";

export default class V2 extends Version {
  /**
   * Initialize the V2 version of Verify
   *
   * @param domain - The Kandy (Kandy.Verify) domain
   */
  constructor(domain: VerifyBase) {
    super(domain, "v2");
  }

  /** forms - { Kandy.Verify.V2.FormListInstance } resource */
  protected _forms?: FormListInstance;
  /** safelist - { Kandy.Verify.V2.SafelistListInstance } resource */
  protected _safelist?: SafelistListInstance;
  /** services - { Kandy.Verify.V2.ServiceListInstance } resource */
  protected _services?: ServiceListInstance;
  /** templates - { Kandy.Verify.V2.TemplateListInstance } resource */
  protected _templates?: TemplateListInstance;
  /** verificationAttempts - { Kandy.Verify.V2.VerificationAttemptListInstance } resource */
  protected _verificationAttempts?: VerificationAttemptListInstance;
  /** verificationAttemptsSummary - { Kandy.Verify.V2.VerificationAttemptsSummaryListInstance } resource */
  protected _verificationAttemptsSummary?: VerificationAttemptsSummaryListInstance;

  /** Getter for forms resource */
  get forms(): FormListInstance {
    this._forms = this._forms || FormListInstance(this);
    return this._forms;
  }

  /** Getter for safelist resource */
  get safelist(): SafelistListInstance {
    this._safelist = this._safelist || SafelistListInstance(this);
    return this._safelist;
  }

  /** Getter for services resource */
  get services(): ServiceListInstance {
    this._services = this._services || ServiceListInstance(this);
    return this._services;
  }

  /** Getter for templates resource */
  get templates(): TemplateListInstance {
    this._templates = this._templates || TemplateListInstance(this);
    return this._templates;
  }

  /** Getter for verificationAttempts resource */
  get verificationAttempts(): VerificationAttemptListInstance {
    this._verificationAttempts =
      this._verificationAttempts || VerificationAttemptListInstance(this);
    return this._verificationAttempts;
  }

  /** Getter for verificationAttemptsSummary resource */
  get verificationAttemptsSummary(): VerificationAttemptsSummaryListInstance {
    this._verificationAttemptsSummary =
      this._verificationAttemptsSummary ||
      VerificationAttemptsSummaryListInstance(this);
    return this._verificationAttemptsSummary;
  }
}
