name: Test and Deploy
on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run automatically at 8AM PST Monday-Friday
    - cron: '0 15 * * 1-5'
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        node: [ 14, 16, 18, lts/* ]
    steps:
      - name: Checkout kandy-node
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - run: npm install
      - name: Run Unit Tests
        run: npm run ci

      - name: Run Cluster Tests
        if: (!github.event.pull_request.head.repo.fork)
        env:
          KANDY_ACCOUNT_SID: ${{ secrets.KANDY_ACCOUNT_SID }}
          KANDY_API_KEY: ${{ secrets.KANDY_CLUSTER_TEST_API_KEY}}
          KANDY_API_SECRET: ${{ secrets.KANDY_CLUSTER_TEST_API_KEY_SECRET }}
          KANDY_FROM_NUMBER: ${{ secrets.KANDY_FROM_NUMBER }}
          KANDY_TO_NUMBER: ${{ secrets.KANDY_TO_NUMBER }}
          KANDY_AUTH_TOKEN: ${{ secrets.KANDY_AUTH_TOKEN }}
        run: |
          npm pack
          tar -xzf kandy*.tgz
          cd spec/cluster
          npm install
          npm run test
